name: CI
on:
  - push
  - pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_OPTS: -Djdk.io.File.enableADS=true

jobs:
  examples-gem:
    name: Examples / Gem
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.0.6
          - 3.1.4
          - 3.2.2
          - 3.3.0-preview3
          - jruby-9.4.5.0
          - truffleruby-23.1.1
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          - os: windows-latest
            ruby: 3.3.0-preview3
          - os: windows-latest
            ruby: truffleruby-23.1.1
    defaults:
      run:
        working-directory: examples/gem
    steps:
      - uses: actions/checkout@v4
      - uses: p0deje/setup-bazel@0.1.0
      - run: echo 'RUBY_VERSION = "${{ matrix.ruby }}"' > ruby_version.bzl
      - run: bazel build ...
      - run: bazel run lib/gem:add-numbers 2
      - run: bazel run lib/gem:print-version
      - run: bazel test ...
      - if: failure() && runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

  ruleset:
    name: Ruleset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bazel run :buildifier.check
      - run: bazel test ...
