name: CI
on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  examples-gem:
    name: Examples / Gem
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby:
          - 2.7.6
          - 3.0.4
          - truffleruby-22.3.0
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          - os: windows-latest
            ruby: truffleruby-22.3.0
    defaults:
      run:
        working-directory: examples/gem
    steps:
      - uses: actions/checkout@v3
      - if: matrix.os == 'windows-latest'
        run: echo "startup --output_user_root=D:/" >> .bazelrc
      - run: echo 'RUBY_VERSION = "${{ matrix.ruby }}"' > ruby_version.bzl
      - run: bazel build ...
      - run: bazel run lib/gem:print-version
      - run: bazel run :rubocop
      - run: bazel test spec/...

  stardoc:
    name: Stardoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bazel build docs/...
