name: CI
on:
  - push
  - pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  examples-gem:
    name: Examples / Gem
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7.8
          - 3.0.6
          - 3.1.4
          - 3.2.2
          - jruby-9.3.10.0
          - jruby-9.4.2.0
          - truffleruby-22.3.1
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          - os: windows-latest
            ruby: truffleruby-22.3.1
    defaults:
      run:
        working-directory: examples/gem
    steps:
      - uses: actions/checkout@v3
      - uses: p0deje/setup-bazel@0.1.0
      - run: echo 'RUBY_VERSION = "${{ matrix.ruby }}"' > ruby_version.bzl
      - run: bazel build ...
      - run: bazel run lib/gem:add-numbers 2
      - run: bazel run lib/gem:print-version
      - run: bazel test ...
      - if: failure() && runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

  stardoc:
    name: Stardoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bazel build docs/...
